configfile: "config/default.yml"
figures_dict=config['figures']

rule targets:
    input:
        expand("submission/figure_{fig_num}.png", 
                fig_num = range(1, len(figures_dict)+1))

rule plot_alpha_beta:
    input:
        R='workflow/scripts/plot_alpha_beta.R'
    output:
        tiff='figures/alpha_beta.tiff'
    conda: 'envs/Rtidy.yml'
    script:
        'scripts/plot_alpha_beta.R'


rule plot_false_pos:
    input:
        R='workflow/scripts/plot_false_pos.R'
    output:
        tiff='figures/false_pos.tiff'
    conda: 'envs/Rtidy.yml'
    script:
        'scripts/plot_false_pos.R'

rule convert_tiff_to_png:
    input:
        tiff=lambda wildcards: f"{figures_dict[int(wildcards.fig_num)]}"
    output:
        png="submission/figure_{fig_num}.png"
    conda: 'envs/shell.yml'
    shell:
        """
        convert {input.tiff} {output.png}
        """
